### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by a001li** [Xlong99/book_Recommend#1]
只能显示注册登录界面

**Comment by Xlong99** [comment]
f12看一下请求记录和后端log

**Comment by a001li** [comment]
可以帮忙远程调试一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xlong99/book_Recommend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月18日(星期一) 晚上8:34
***@***.***&gt;;
抄送:&nbsp;"右转 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xlong99/book_Recommend] 运行出错 (Issue #1)





 
f12看一下请求记录和log
