### ISSUE TITLE
能否提供一下创建表的sql

### ISSUE THREAD

**Issue by SmallseaTT** [Xlong99/book_Recommend#2]
最好附带一下一些样例数据，谢谢

**Comment by Xlong99** [comment]
表结构不复杂，如有需求可以从实体类逆向

**Comment by SmallseaTT** [comment]
可是样例数据莫得啦，求求大佬了0.0

**Comment by deng-deng-cy** [comment]
me,too.主要是比较需要样例数据，大佬

**Comment by Xlong99** [comment]
`/*
 Navicat Premium Data Transfer

 Source Server         : book
 Source Server Type    : MySQL
 Source Server Version : 50650
 Source Host           : 121.40.134.218:3306
 Source Schema         : book

 Target Server Type    : MySQL
 Target Server Version : 50650
 File Encoding         : 65001

 Date: 23/05/2022 20:22:51
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for book
-- ----------------------------
DROP TABLE IF EXISTS `book`;
CREATE TABLE `book`  (
  `book_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `book_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_croatian_ci NULL DEFAULT NULL,
  `author` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `publisher` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `introduction` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `book_status` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `pubdate` timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00',
  `location` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `gmt_modified` timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00',
  `gmt_create` timestamp(0) NOT NULL DEFAULT '2000-01-10 00:00:00',
  `photo_url` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `modifier` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  PRIMARY KEY (`book_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 73 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for borrow
-- ----------------------------
DROP TABLE IF EXISTS `borrow`;
CREATE TABLE `borrow`  (
  `borrow_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `book_id` bigint(20) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  `borrow_date` timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00',
  `back_date` timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00',
  `borrow_status` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `gmt_modified` timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00',
  `gmt_create` timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00',
  `modifier` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `goal` int(10) NULL DEFAULT NULL,
  PRIMARY KEY (`borrow_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 55 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for recommend
-- ----------------------------
DROP TABLE IF EXISTS `recommend`;
CREATE TABLE `recommend`  (
  `recommend_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `book_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `author` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `user_id` bigint(20) NULL DEFAULT NULL,
  `gmt_modified` timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00',
  `gmt_create` timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00',
  `modifier` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `recommend_type` int(255) NULL DEFAULT NULL,
  PRIMARY KEY (`recommend_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1170898 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for taste_pref
-- ----------------------------
DROP TABLE IF EXISTS `taste_pref`;
CREATE TABLE `taste_pref`  (
  `user_id` bigint(20) NOT NULL,
  `item_id` bigint(20) NOT NULL,
  `pref_value` float NOT NULL,
  PRIMARY KEY (`user_id`, `item_id`) USING BTREE,
  INDEX `　　　　user_id`(`user_id`) USING BTREE,
  INDEX `　　　　item_id`(`item_id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for union_book
-- ----------------------------
DROP TABLE IF EXISTS `union_book`;
CREATE TABLE `union_book`  (
  `union_book_id` bigint(11) NOT NULL AUTO_INCREMENT COMMENT '唯一图书索引，书名和作者相同的表示同一本书',
  `book_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '书名',
  `author` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '作者',
  PRIMARY KEY (`union_book_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 36 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`  (
  `user_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `username` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `password` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `user_status` varchar(20) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL,
  `gmt_modified` timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00',
  `gmt_create` timestamp(0) NOT NULL DEFAULT '2000-01-01 00:00:00',
  `email` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `modifier` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `phone_number` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `sex` int(255) NOT NULL,
  `age` int(100) NOT NULL,
  `profession` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`user_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 151 CHARACTER SET = latin1 COLLATE = latin1_swedish_ci ROW_FORMAT = Compact;

SET FOREIGN_KEY_CHECKS = 1;
`

**Comment by SmallseaTT** [comment]
谢谢大佬，十分感谢
